### ISSUE TITLE
[API] As a User, I can sign up and sign in/out with a username and password

### ISSUE THREAD

**Issue by malparty** [malparty/google-search-ruby#17]
Build API for #5 

## Why?
In order to provide a secure data segregation within the application.

### Additional notes:
Authentication shall be available from web UI as well as API (Oauth 2 RESTful JSON API ).
UI here will be minimal. Advanced UI being done in #16 

## Who Benefits?
Non logged Users

**Comment by junan** [comment]
![Screen Shot 2021-06-07 at 6 10 58 PM](https://user-images.githubusercontent.com/6076762/121010042-17635980-c7bf-11eb-8e1f-ff7672a15722.png)


@malparty Just for your information, Sign up and Logout API is optional for the IC. If you want to skip those you can do. Or if you don't want to skip those, it is also fine 😄 

https://www.notion.so/nimblehq/Internal-Certifications-123ba28275654192ba31011b9e20bed4
