### ISSUE TITLE
Backlog Management: Issue format

### ISSUE THREAD

**Issue by ankitkalia1195** [malparty/google-search-ruby#21]
## What Happened

* The issues are not following our convention https://github.com/nimblehq/git-template/tree/main/.github/ISSUE_TEMPLATE.

## Expectation

The issues should match the format, something similar to https://github.com/junan/elixir_google_scraper/issues/6

**Comment by malparty** [comment]
Is it okay if I add some "Additional notes" (purely informative to me) as a 3rd part? 
Like here: #5 
Thanks,

**Comment by malparty** [comment]
Another question: For FrontEnd and API tasks (which relate to the same "User Story"), is it ok to put only the reference, or do you expect a raw Copy/Paste of the description? :) 
Thanks,

**Comment by ankitkalia1195** [comment]
> Is it okay if I add some "Additional notes" (purely informative to me) as a 3rd part?

Sure you can add, but can reduce the heading size for additional notes I guess :).

**Comment by malparty** [comment]
Perfect! I'll update that. 
PS: I made a mistake in the commit reference bellow, I'll be careful for the next one ><

**Comment by ankitkalia1195** [comment]
> Another question: For FrontEnd and API tasks (which relate to the same "User Story"), is it ok to put only the reference, or do you expect a raw Copy/Paste of the description? :)
> Thanks,

For this I guess copy/paste should be better, usually thats what PMs do here at nimble.

**Comment by malparty** [comment]
Heavy! But well noted, I'll do it ;-)

**Comment by malparty** [comment]
Should be good now! :) Feel free to re-open if you have any concerns.
Thanks! :)
