### ISSUE TITLE
Do not commit anything directly to develop branch.

### ISSUE THREAD

**Issue by ankitkalia1195** [malparty/google-search-ruby#22]
## Why

We should not be committing anything directly to develop branch such as https://github.com/malparty/google-search-ruby/commits/develop. Just a initial commit with blank readme file maybe be enough, and then everything gets merged via PR, even if it is created via Rails template

## Who Benefits

The reviewer mainly.

**Comment by malparty** [comment]
Well noted, I thought that the project initialization could be done directly in develop branch. But PR indeed makes it easier to follow-up for you. My bad.

I reverted all changes in `develop` (by adding a last commit that remove all files). 
I will re-deploy the template in a `chore/project-init` branch.
