### ISSUE TITLE
Create a issue/ticket for listing user Keywords

### ISSUE THREAD

**Issue by junan** [malparty/google-search-ruby#23]
Currently I am missing a ticket for listing uploaded keywords Like the bellow image(ignore wrong action field 😄  )
![Screen Shot 2021-06-07 at 6 55 24 PM](https://user-images.githubusercontent.com/6076762/121012976-7d9dab80-c7c2-11eb-91e4-c0abcab73615.png)

Then when user will check the `show` it will show the details google response result.

This listing keywords page can be used in the dashboard page or homepage. What do you think?

**Comment by malparty** [comment]
According to what I had in mind, it was included in the #12 
As there is little data to show, my plan was to reuse some partial views (1 single keyword card) for both screens (`list keywords` & `show keyword results`  results), just adding the Raw Html preview on the `show keyword results` screen. 

If you believe it's still worth to have 2x separate user stories (and so 2 distinct pull requests), I understand and I will add the new BackEnd/Front End tasks.

**Comment by malparty** [comment]
Added as #25, #26 & #27. ;-)
