### ISSUE TITLE
Missing ticket/issue for password reset

### ISSUE THREAD

**Issue by junan** [malparty/google-search-ruby#24]
I am missing the user password ticket. I think you can create a ticket for reseting password(No need for API I think)

![Screen Shot 2021-06-07 at 7 04 58 PM](https://user-images.githubusercontent.com/6076762/121013659-5398b900-c7c3-11eb-90b8-f8d7528ab138.png)

**Comment by malparty** [comment]
Ok, my bad. From your comment, I believe Devise is not like in .Net Identity package where all these sub-features come packed and you just configure them. 

If there is new screen creations for this specific behavior, then I'll add these tasks: #28 & #29. ;-)
