### ISSUE TITLE
Configure UI test automation

### ISSUE THREAD

**Issue by malparty** [malparty/google-search-ruby#3]
## Why?
Save time with automation and enforce quality checks by:
- Enable UI test execution via GitHub Actions on PR creation/updates.
- Enforce UI tests before PR validation/merge.

## Who Benefits?
Development team

**Comment by malparty** [comment]
@ankitkalia1195  @junan after some tests (and learning/hands-on), the initial config is already working, no need to change any line of code. 
So I will pass this issue as "Ready for QA" without using the step "In Code Review".
Feel free to tell me if such practice is not ok -- and eventually how to handle such case in a better way ;-)
Thanks!

**Comment by junan** [comment]
@malparty As it is already working with the initial config. So I think there is no need for "In Code Review" in this case as there are no changes in the code.
