### ISSUE TITLE
Configure deployment automation

### ISSUE THREAD

**Issue by malparty** [malparty/google-search-ruby#4]
## Why?

Ensure no manual action is made for deployment, thus reducing the risks for human errors.
Increase traceability of events while enforce PR & validations before any deployment.

### Additional notes:
Define which hosting provider to use (Heroku, AWS, Google Cloud or Digital Ocean)
Configure auto-deploy for 2 environments:

- Staging: `develop` branch
- Production: `main` branch

## Who Benefits?
Project team & stakeholders

**Comment by junan** [comment]
> Staging: release/* branches
 
 @malparty The `develop` branch should be used for staging. For staging we don't create any Release PR. Once we merge a PR into `develop` branch, it should be deployed to staging server automatically(via github action)

**Comment by malparty** [comment]
Well noted, task description updated accordingly, thanks! :)
